table Lens
	lineageTag: c7c4cd3b-c058-5ac7-98b4-62ab25fa6435

	column Lens
		dataType: string
		lineageTag: 6025becb-818e-5934-9b1f-0687f49c261c
		summarizeBy: none
		sortByColumn: LensOrder
		sourceColumn: Lens

	column LensOrder
		dataType: int64
		formatString: 0
		lineageTag: c43cb9fd-7e27-5d64-965a-83f6b71dbf75
		summarizeBy: none
		sourceColumn: LensOrder

	column Caption
		dataType: string
		lineageTag: 68f8b1bf-3974-5292-98c9-076943b08283
		summarizeBy: none
		sourceColumn: Caption

	partition Lens = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(DataFolder & "Lens.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				  Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				  Typed = Table.TransformColumnTypes(Promoted, {{"Lens", type text}, {"LensOrder", Int64.Type}, {"Caption", type text}}, "en-US")
				in
				  Typed

	annotation PBI_ResultType = Table
